### ISSUE TITLE
add support for unicode characters beyond 0xFFFF

### ISSUE THREAD

**Issue by shayangz** [sendgrid/smtpapi-java#12]
These days, it's very common to have unicode characters that require surrogate pairs to be represented in Java Strings. Currently the library doesn't seem to be able to handle these. 

It would very helpful to either build that support into the library or provide a way to pass that info in somehow for proper rendering.

Thanks in advance 🙏

**Comment by thinkingserious** [comment]
Hello @shayangz,

Thanks for the request. Can you please provide an example test case?

With Best Regards,

Elmer
