### ISSUE TITLE
Does the Settings (Filters) Support Multiple BCCs?

### ISSUE THREAD

**Issue by jswart** [sendgrid/smtpapi-java#79]
#### Issue Summary

I am broadening the [google-app engine java](https://github.com/sendgrid/sendgrid-google-java/blob/master/Sendgrid.java) to cc as well as bcc multiple groups.

Does the SMTP API support multiple bccs? For example:

    "filters": {
        "bcc": {
            "settings": {
                "email": "test1@test.com,test2@test.com",
                "enable": "1"
            }
        }
    }

I can get the single email to work, but not multiple. Is it a formatting issue?

**Comment by thinkingserious** [comment]
Hello @jswart,

Only one email address may be entered in this field, if you wish to distribute BCCs to multiple addresses you will need to create a distribution group or use forwarding rules.

Thanks!

With Best Regards,

Elmer
