### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/smtpapi-java#83]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by aquibbaig** [comment]
can i take up this issue?

**Comment by thinkingserious** [comment]
It's all yours @aquibbaig! Thanks!
